language: java
jdk: openjdk8
cache:
  directories:
  - "$HOME/.m2"
before_install: cd company
install: true
script: mvn -B test
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: nWkuOVjpSmJqoTVJBkc16DnkLYsuVjqLuWrDaC2dYCrv9A9ucdlpof7/zxGj0CCW+7/AdfOEz+ynhtKbedHprh/qpOR9axpM6aZDYq6cnEdW2SgWwoo0pUg2Sx6R0uR5nIPnmihO6HA7EzcKcJ3Deo8efb/0CSN6vnXmhAYL/r/x+3+al9uhdaL/GtT1GDcA5fsBT8R/Cm99z8XX7Iax0mO7ufxpghqg5MP7QouWLesjF4v9zZkRnK8mHviFiOrDQ9MyngU6W18vENzcup5dxA1RWu0T6XWrAf8hI+4rXCEgW+3A7jITZfqgRDZM7U3T4YL0wQWHQqGfiYF8R+vLyi7BuYtcr60uY2Se2nLdfHGap6gUj2Vj01DZhof8g+fa3y/vl7u+/ik2lqKvxOLjBL2ovQNBqbpoNWpi/fdF41b283IzieknPjbj9L20QG79kAXJ9sQoDdTIEuXoY0c2XfdcPM91wU3pwTNX/SmcscErQEzgf5VgHSKpQ/Rw7wOsV00DhO4NAqovTLfD9V3Rmi20RSVXGpR27UQW6+SJRXHSrMXd8Z7c7ZhJwrWox25LLq69PU8pRlblTRsEwZDPzy56D32jm80pKOhYDOQtU6zJLyaQMFa9NTUc8R0hh0CZOrm8m2U1iy9eEV9Fe55jXDQFFOmy5Gm7FTPOPapQUys=
  app: fullstack-company-app
  on: master
