language: java

jdk: openjdk8

cache: 
  directories:
    - $HOME/.m2

before_install: cd company

install: true

script: mvn -B test

deploy:
  skip_cleanup: true
  provider: heroku

  api_key:
    secure: 'eif1Jsg0tFUqKe4LFAC3cwPo7NQTWQXpsYlbYN2GB14E89NiAbjlsynzjE294CuEEOethe5p2lBWNES2MR8anUQ2cHuKRnRHFJPlQdJL0dPuQyU5PyGG1SIRWdyoWOzs5tqSmsuOWEBXi8xLxC8ePRi5MXA9tEkrlj570qrCC7uLtoHLPzuwvZ/SvlhsKQ+zZHLepK4dDNso2p4GHoX1efPIyUxLhf0NwZrDf8tc2NtyLNFY+jUBUW2hC1hAnx3mZL2S2fmsiNY954MRbGSYsrhITM5nvz5CKHYTMa8s01xaziT1qIHGikbfL8I/tXq9Tt9wYuHX/pjTPueg/FPJf48y9aT3Nk1tfeS7Q5SgW3U3XWHK3wNx43sceaYcKahF7Bnev7Zeay2ZnJ5JPk6Co9LUXPJ7Zv/QcKeVip9jYXBj1xWVZxkl03OnO7hHHh1bTKuhg1K+BgJJb9ehb9nkn/0ktq0GCYUzlTwEX/9BxgFPdrwiOc5JJU+TZUOOIVoXoTQk19cOxpddx5+a0rtoQFEcgqqfT+iBceMIP0wNZ0xKWylR24wC7sQTeKYf3eH5JYA8sse227LJLyoARom3nYDL473gY0a/K9CH8ezV+svz7CWrGPumdztR/tNTlG7y+JH2h9h708+skYHOcmlxp89iytBFuY9FZZxpgrgQji4='
    
  app: fullstack-company-app
  on: master
